on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'

name: Publish Trickster Release Candidate to Drafts

jobs:
  release:
    uses: ./.github/workflows/publish-release.yml
    with:
      draft: true
      prerelease: true
      job-suffix: 'Release Candidate'
